# Generated by Django 3.0.5 on 2020-04-04 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("especialidades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "biografia",
                    models.TextField(blank=True, null=True, verbose_name="Biografía"),
                ),
                (
                    "numero_colegio_medico",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Número de Colegio Médico",
                    ),
                ),
                (
                    "centro_laboral",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Centro laboral",
                    ),
                ),
                (
                    "experiencia_en_anios",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Años de experiencia"
                    ),
                ),
                (
                    "validado",
                    models.BooleanField(default=False, verbose_name="¿Validado?"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha y hora de creación",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y hora de actualización",
                    ),
                ),
                (
                    "validado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha y hora de validación",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="especialidades.Especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persona.Persona",
                        verbose_name="Persona",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario asociado",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicos_validados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario validador",
                    ),
                ),
            ],
            options={"verbose_name": "médico", "verbose_name_plural": "médicos",},
        ),
    ]
