# Generated by Django 3.0.5 on 2020-04-17 04:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio_disponibilidad', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del periodo')),
                ('fin_disponibilidad', models.DateTimeField(blank=True, null=True, verbose_name='Fin del periodo')),
                ('turnos', models.CharField(blank=True, choices=[('monday_morning', 'Lunes de 8am a 12m'), ('monday_evening', 'Lunes de 12m a 4pm'), ('monday_night', 'Lunes de 4pm a 8pm'), ('tuesday_morning', 'Martes de 8am a 12m'), ('tuesday_evening', 'Martes de 12m a 4pm'), ('tuesday_night', 'Martes de 4pm a 8pm'), ('wednesday_morning', 'Miércoles de 8am a 12m'), ('wednesday_evening', 'Miércoles de 12m a 4pm'), ('wednesday_night', 'Miércoles de 4pm a 8pm'), ('thursday_morning', 'Jueves de 8am a 12m'), ('thursday_evening', 'Jueves de 12m a 4pm'), ('thursday_night', 'Jueves de 4pm a 8pm'), ('friday_morning', 'Viernes de 8am a 12m'), ('friday_evening', 'Viernes de 12m a 4pm'), ('friday_night', 'Viernes de 4pm a 8pm'), ('saturday_morning', 'Sábado de 8am a 12m'), ('saturday_evening', 'Sábado de 12m a 4pm'), ('saturday_night', 'Sábado de 4pm a 8pm')], max_length=50, null=True, verbose_name='Turno de Disponibilidad Horaria')),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medicos.Medico', verbose_name='Ejecutado por')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
            },
        ),
    ]
