# Generated by Django 3.0.5 on 2020-04-17 05:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='turnos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday_morning', 'Lunes de 8am a 12m'), ('monday_evening', 'Lunes de 12m a 4pm'), ('monday_night', 'Lunes de 4pm a 8pm'), ('tuesday_morning', 'Martes de 8am a 12m'), ('tuesday_evening', 'Martes de 12m a 4pm'), ('tuesday_night', 'Martes de 4pm a 8pm'), ('wednesday_morning', 'Miércoles de 8am a 12m'), ('wednesday_evening', 'Miércoles de 12m a 4pm'), ('wednesday_night', 'Miércoles de 4pm a 8pm'), ('thursday_morning', 'Jueves de 8am a 12m'), ('thursday_evening', 'Jueves de 12m a 4pm'), ('thursday_night', 'Jueves de 4pm a 8pm'), ('friday_morning', 'Viernes de 8am a 12m'), ('friday_evening', 'Viernes de 12m a 4pm'), ('friday_night', 'Viernes de 4pm a 8pm'), ('saturday_morning', 'Sábado de 8am a 12m'), ('saturday_evening', 'Sábado de 12m a 4pm'), ('saturday_night', 'Sábado de 4pm a 8pm'), ('sunday_morning', 'Domingo de 8am a 12m'), ('sunday_evening', 'Domingo de 12m a 4pm'), ('sunday_night', 'Domingo de 4pm a 8pm')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
