# Generated by Django 3.0.5 on 2020-04-17 22:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20200417_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='turnos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday_morning', 'Lunes (Mañana)'), ('monday_evening', 'Lunes (Tarde)'), ('monday_night', 'Lunes (Noche)'), ('tuesday_morning', 'Martes (Mañana)'), ('tuesday_evening', 'Martes (Tarde)'), ('tuesday_night', 'Martes (Noche)'), ('ednesday_morning', 'Miércoles (Mañana)'), ('ednesday_evening', 'Miércoles (Tarde)'), ('ednesday_night', 'Miércoles (Noche)'), ('thursday_morning', 'Jueves (Mañana)'), ('thursday_evening', 'Jueves (Tarde)'), ('thursday_night', 'Jueves (Noche)'), ('friday_morning', 'Viernes (Mañana)'), ('friday_evening', 'Viernes (Tarde)'), ('friday_night', 'Viernes (Noche)'), ('saturday_morning', 'Sábado (Mañana)'), ('saturday_evening', 'Sábado (Tarde)'), ('saturday_night', 'Sábado (Noche)')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
