- hosts: apps 
  gather_facts: false
  become: true

  tasks:
    - name: cambiar puerto 23201 en server.xml
      replace:
        path: /servers/tomcat{{item}}/conf/server.xml
        regexp: "23201"
        replace: "2320{{item}}" 
      with_items:
        ["5","6","7","8"]

    - name: cambiar puerto 23301 en server.xml
      replace:
        path: /servers/tomcat{{item}}/conf/server.xml
        regexp: "23301"
        replace: "2330{{item}}" 
      with_items:
        ["5","6","7","8"]

    - name: cambiar puerto 23401 en server.xml
      replace:
        path: /servers/tomcat{{item}}/conf/server.xml
        regexp: "23401"
        replace: "2340{{item}}" 
      with_items:
        ["5","6","7","8"]





