- hosts: webs, apps, solar 
  gather_facts: false
  become: true

  tasks:
    - name: nofile soft limit 
      pam_limits:
        domain: "*"
        limit_type: soft
        limit_item: nofile
        value: "400000"
     
    - name: nofile hard limit 
      pam_limits:
        domain: "*"
        limit_type: hard
        limit_item: nofile
        value: "400000"

    - name: noproc soft limit 
      pam_limits:
        domain: "*"
        limit_type: soft
        limit_item: nproc
        value: "65000"
     
    - name: noproc hard limit 
      pam_limits:
        domain: "*"
        limit_type: hard
        limit_item: nproc
        value: "65000"

    - name: cambiar 20-nproc.conf 
      lineinfile:
        create: true
        dest: /etc/security/limits.d/20-nproc.conf
        regexp: ^\*          soft    nproc 
        line: "*          soft    nproc   65000"

