- hosts: solar
  become: true
  vars:
     var_sshd_set_keepalive: !!str 0
     sshd_idle_timeout_value: !!str 900
     sshd_login_level: "INFO"
     root_login: "no"

  tasks:  
    - name: Install basic packages
      package:
        name: ['nmap']
        state: present

    - name: Change timezone to Lima
      timezone:
        name: "America/Lima"  

    - name: Disabling IPv6 Networking
      lineinfile:
        dest: /etc/sysconfig/network
        line: NETWORKING_IPV6=no
        state: present

    - name: Disabling IPv6 core
      lineinfile:
        dest: /etc/sysconfig/network
        line: IPV6INIT=no
        state: present

    - name: Allow Only SSH Protocol 2
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: ^Protocol [0-9]
        line: Protocol 2
        validate: /usr/sbin/sshd -t -f %s
    
    - name: Set SSH Client Alive Count
      lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^ClientAliveCountMax
        line: ClientAliveCountMax {{ var_sshd_set_keepalive }}
        validate: /usr/sbin/sshd -t -f %s
      notify: restart sshd
    
    - name: Disable SSH Root Login
      lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^PermitRootLogin
        line: PermitRootLogin {{ root_login }}
        insertafter: (?i)^#?authentication
        validate: /usr/sbin/sshd -t -f %s
      notify: restart sshd
    
    - name: Set SSH Idle Timeout Interval
      lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^ClientAliveInterval
        line: ClientAliveInterval {{ sshd_idle_timeout_value }}
        validate: /usr/sbin/sshd -t -f %s
    
    - name: Permitir temporalmente passwords
      lineinfile:
        create: true
        dest: /etc/ssh/sshd_config   
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication yes
        validate: /usr/sbin/sshd -t -f %s  

    - name: Set LogLevel to INFO
      lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^LogLevel
        line: LogLevel {{ sshd_login_level }}
        validate: /usr/sbin/sshd -t -f %s
      notify: restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
