# Generated by Django 3.0.5 on 2020-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Categoría"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="A mayor peso menor precedencia en el listado",
                        verbose_name="Peso",
                    ),
                ),
            ],
            options={
                "verbose_name": "especialidad",
                "verbose_name_plural": "especialidades",
                "ordering": ("weight", "nombre"),
            },
        ),
    ]
