# Generated by Django 3.0.5 on 2020-04-04 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, null=True, verbose_name="Perfil en LikedIn"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True, null=True, verbose_name="Perfil en Facebook"
                    ),
                ),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Número Whatsapp",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "telefono_fijo",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Teléfono fijo",
                    ),
                ),
                (
                    "telefono_movil",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Teléfono móvil",
                    ),
                ),
            ],
            options={"verbose_name": "contacto", "verbose_name_plural": "contactos",},
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombres", models.CharField(max_length=128, verbose_name="Nombres")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=128, verbose_name="Apellido paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Apellido materno",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("dni", "D.N.I."),
                            ("ce", "C.E."),
                            ("pa", "Pasaporte"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=64, verbose_name="Número de documento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "pais_de_origen",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="País de orígen",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha y hora de creación",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y hora de actualización",
                    ),
                ),
                (
                    "contacto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persona.Contacto",
                        verbose_name="Contactos",
                    ),
                ),
            ],
            options={
                "verbose_name": "persona",
                "verbose_name_plural": "personas",
                "ordering": ["apellido_paterno", "apellido_materno", "nombres"],
                "unique_together": {("tipo_documento", "numero_documento")},
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("PACIE", "Paciente"),
                            ("MEDIC", "Medico"),
                            ("MINSA", "Minsa"),
                        ],
                        max_length=5,
                        verbose_name="Tipo de perfil",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="persona",
                        to="persona.Persona",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "unique_together": {("usuario", "perfil")},
            },
        ),
    ]
