# Generated by Django 3.0.5 on 2020-04-04 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                ("nombre", models.CharField(max_length=128, verbose_name="Origen")),
                (
                    "home",
                    models.CharField(
                        max_length=64, verbose_name="Ruta registrada en django"
                    ),
                ),
                (
                    "ruta",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Ruta absoluta"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        max_length=128, upload_to="Roles/avatar/", verbose_name="Avatar"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "creada_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha y hora de creación",
                    ),
                ),
                (
                    "actualizada_en",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y hora de actualización",
                    ),
                ),
            ],
            options={"verbose_name": "Rol", "verbose_name_plural": "Roles",},
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persona.Persona",
                        verbose_name="Persona",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="permisos.Rol",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "unique_together": {("usuario", "rol")},
            },
        ),
    ]
