# Generated by Django 3.0.5 on 2020-04-04 03:50

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombres", models.CharField(max_length=128, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=128, verbose_name="Apellidos"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("dni", "D.N.I."),
                            ("ce", "C.E."),
                            ("pa", "Pasaporte"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=64, verbose_name="Número de documento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Teléfono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                ("lugar", models.CharField(max_length=255, verbose_name="Lugar")),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha y hora de creación",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y hora de actualización",
                    ),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "paciente",
                "unique_together": {("tipo_documento", "numero_documento")},
            },
        ),
    ]
